name: check-changelog

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  check-changelog-updated:
    name: Check changesets directory
    runs-on: ubuntu-latest
    if: ${{ !contains( github.event.pull_request.labels.*.name, 'no-changelog-update') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install deps
        run: python -m pip install pyyaml
      - name: Added a changeset
        run: |
          ls changesets | grep "pr_${{ github.event.number }}.md" || echo "There is no changeset file for this PR!"
      - name: Check content of changeset file
        run: python scripts/check_changeset.py --pr ${{ github.event.number }}